export const certificates = [
  {
    id: 1,
    title: 'Data Analytics Job Simulation',
    issuer: 'Deloitte',
    date: '2026',
    category: 'Data Analytics',
    driveLink: 'https://drive.google.com/file/d/1zg6m_bDroJHgz9Bv6bSEAZpCjvWQVT1t/view?usp=drive_link',
    color: 'from-blue-500 to-cyan-600',
    accent: '#22d3ee',
  },
  {
    id: 2,
    title: 'Build Your Own GPTs',
    issuer: 'LinkedIn Learning',
    date: '2025',
    category: 'AI/ML',
    driveLink: 'https://drive.google.com/file/d/1HMg3LNSVUJ4omxJWBFl5YnDcVqjelYwz/view?usp=sharing',
    color: 'from-indigo-500 to-purple-600',
    accent: '#818cf8',
  },
  {
    id: 3,
    title: 'Introduction to Artificial Intelligence (2023)',
    issuer: 'LinkedIn Learning',
    date: '2025',
    category: 'AI/ML',
    driveLink: 'https://drive.google.com/file/d/1eYAmbvjpHk4kYHKr2vRwwR1QIevppxai/view?usp=sharing',
    color: 'from-emerald-500 to-teal-600',
    accent: '#6ee7b7',
  },
  {
    id: 4,
    title: 'Learning Git and GitHub',
    issuer: 'LinkedIn Learning',
    date: '2025',
    category: 'Cloud & DevOps',
    driveLink: 'https://drive.google.com/file/d/1T6ZS2GPRA9AgikyfYhstQF-AOo4ruP9V/view?usp=sharing',
    color: 'from-amber-500 to-orange-600',
    accent: '#fb923c',
  },
  {
    id: 5,
    title: 'Interview Skills',
    issuer: 'TCS iON',
    date: '2025',
    category: 'Professional Skills',
    driveLink: 'https://drive.google.com/file/d/1ed1dW9jTkcRvXbQj5NVYlW0q4Uc6cyHI/view?usp=sharing',
    color: 'from-rose-500 to-pink-600',
    accent: '#f472b6',
  },
  {
    id: 6,
    title: 'Software Engineering Job Simulation',
    issuer: 'Tom Brunskill',
    date: '2025',
    category: 'Development',
    driveLink: 'https://drive.google.com/file/d/1bTqZpWwB0MyasXMnYCzpJpOIbEmFQgJ0/view?usp=sharing',
    color: 'from-violet-500 to-indigo-600',
    accent: '#a78bfa',
  },
  {
    id: 7,
    title: 'Data Analyst with ML Essentials',
    issuer: 'iamneo',
    date: '2026',
    category: 'Data Analytics',
    driveLink: 'https://drive.google.com/file/d/1e57BF5iy4VSC-hX8rZ-lXrB6ejtgPv81/view?usp=sharing',
    color: 'from-sky-500 to-blue-600',
    accent: '#22d3ee',
  },
]

export const projects = [
  {
    id: 1,
    title: 'AI Resume Screening Chatbot',
    problem: 'Recruiters waste hours manually screening resumes. Matching the right candidate to a job role requires reading dozens of documents.',
    solution: 'Built a RAG-powered chatbot that ingests multiple PDF resumes, performs semantic search, and automatically extracts skills and experience to rank candidates.',
    architecture: 'PDF → PyPDF2 → HuggingFace Embeddings → FAISS Vector Store → LangChain Retriever → Groq LLaMA 3.1 → Streamlit UI',
    tech: ['Python', 'Streamlit', 'LangChain', 'FAISS', 'HuggingFace', 'Groq LLaMA 3.1'],
    features: ['Upload multiple PDFs', 'Semantic candidate matching', 'Auto skill & experience extraction'],
    result: 'Reduced manual screening time significantly by surfacing the most relevant candidates through natural-language queries.',
    learnings: 'Deep understanding of RAG architectures, vector similarity search, and embedding pipelines.',
    category: 'AI/ML',
    featured: true,
    github: 'https://github.com/DharunKumarS-code/rag-chatbot',
    demo: 'https://rag-chatbot-mjuv6w8amagwrhzfrjdxcj.streamlit.app/',
    color: 'from-indigo-500 to-purple-600',
    accent: '#818cf8',
    pipelineType: 'rag',
  },
  {
    id: 2,
    title: 'Sales Performance Dashboard',
    problem: 'Business stakeholders lacked real-time visibility into sales KPIs, regional performance, and time-based trends.',
    solution: 'Designed an interactive Power BI dashboard with DAX measures, KPI cards, regional maps, and drill-through reports.',
    architecture: 'Raw Sales Data → Excel Cleaning → Power BI Data Model → DAX Measures → Interactive Dashboard',
    tech: ['Power BI', 'DAX', 'Data Modeling', 'Excel'],
    features: ['KPI tracking (revenue, growth)', 'Region & time-based analysis', 'Business decision insights'],
    result: 'Stakeholders gained instant visibility into performance trends, enabling faster data-driven decisions.',
    learnings: 'Data modeling, DAX formula optimization, and translating business questions into visual analytics.',
    category: 'Data Analytics',
    featured: true,
    github: 'https://github.com/DharunKumarS-code/Retail-Sales-Performance-Analysis',
    demo: null,
    color: 'from-emerald-500 to-teal-600',
    accent: '#6ee7b7',
    pipelineType: 'analytics',
  },
  {
    id: 3,
    title: 'Healthcare AI Solution',
    problem: 'Clinical decision-making lacks data-driven support tools, leading to inefficiencies in diagnosis and resource allocation.',
    solution: 'Built an AI-powered healthcare analytics platform providing predictive insights for diagnosis support.',
    architecture: 'Patient Data → Pandas Preprocessing → Scikit-learn ML Models → Evaluation → Prediction Output',
    tech: ['Python', 'Machine Learning', 'Pandas', 'Scikit-learn'],
    features: ['Predictive health analytics', 'Data-driven diagnosis support', 'Efficiency optimization'],
    result: 'Demonstrated measurable improvement in prediction accuracy for the target health outcomes.',
    learnings: 'End-to-end ML pipeline development, handling medical data, and model evaluation metrics.',
    category: 'AI/ML',
    featured: false,
    github: 'https://github.com/DharunKumarS-code/MiniProject',
    demo: null,
    color: 'from-rose-500 to-pink-600',
    accent: '#f472b6',
    pipelineType: 'ml',
  },
  {
    id: 4,
    title: 'Task Management System',
    problem: 'Teams working on software projects need structured task tracking with full documentation and version control integration.',
    solution: 'Built an enterprise-grade task management application with complete SRS documentation, Git workflows, and team collaboration features.',
    architecture: 'Java Backend → Task CRUD → Git Version Control → SRS Documentation → Team Collaboration Layer',
    tech: ['Java', 'Git', 'GitHub', 'SRS Documentation'],
    features: ['Project & task tracking', 'Version control integration', 'Team collaboration'],
    result: 'Delivered a fully documented, working system applying agile principles and structured development cycles.',
    learnings: 'Software requirements engineering, agile project management, and large-scale Java development.',
    category: 'Software Dev',
    featured: false,
    github: 'https://github.com/DharunKumarS-code/Task-Management',
    demo: null,
    color: 'from-amber-500 to-orange-600',
    accent: '#fb923c',
    pipelineType: 'software',
  },
]

export const skills = [
  {
    category: 'Programming',
    items: ['Python', 'Java'],
    color: '#22d3ee',
    icon: '{ }',
  },
  {
    category: 'AI / ML',
    items: ['NLP', 'RAG Pipelines', 'Embeddings', 'LangChain', 'FAISS', 'Scikit-learn'],
    color: '#818cf8',
    icon: '🧠',
  },
  {
    category: 'Data Tools',
    items: ['Power BI', 'Pandas', 'Excel', 'Data Modeling', 'DAX'],
    color: '#6ee7b7',
    icon: '📊',
  },
  {
    category: 'Dev Tools',
    items: ['Git', 'GitHub', 'Streamlit', 'VS Code'],
    color: '#fb923c',
    icon: '⚙️',
  },
  {
    category: 'Databases',
    items: ['MongoDB', 'SQL'],
    color: '#f472b6',
    icon: '🗄️',
  },
  {
    category: 'Concepts',
    items: ['Data Structures', 'Analytics', 'CI/CD Basics', 'OOP', 'REST APIs'],
    color: '#a78bfa',
    icon: '💡',
  },
]

export const skillNodes = [
  { id: 'dharun', label: 'DHARUN', group: 'center', x: 0, y: 0, size: 1.8 },
  { id: 'python', label: 'Python', group: 'programming', x: -2, y: 1, size: 1.2, links: ['langchain', 'faiss', 'pandas', 'scikit'] },
  { id: 'java', label: 'Java', group: 'programming', x: -2, y: -1, size: 1.0, links: ['git'] },
  { id: 'langchain', label: 'LangChain', group: 'ai', x: -3.5, y: 2.5, size: 1.1, links: ['faiss', 'nlp'] },
  { id: 'faiss', label: 'FAISS', group: 'ai', x: -3, y: 0, size: 1.0, links: [] },
  { id: 'nlp', label: 'NLP', group: 'ai', x: -4.5, y: 1, size: 1.0, links: ['genai'] },
  { id: 'genai', label: 'GenAI', group: 'ai', x: -4, y: 3, size: 1.0, links: [] },
  { id: 'scikit', label: 'Scikit-learn', group: 'ai', x: -3.5, y: -1.5, size: 1.0, links: ['pandas'] },
  { id: 'pandas', label: 'Pandas', group: 'data', x: -2, y: -2.5, size: 1.0, links: ['powerbi'] },
  { id: 'powerbi', label: 'Power BI', group: 'data', x: 0.5, y: -3, size: 1.1, links: ['dax'] },
  { id: 'dax', label: 'DAX', group: 'data', x: 2, y: -3.5, size: 0.9, links: [] },
  { id: 'streamlit', label: 'Streamlit', group: 'dev', x: 1, y: 2.5, size: 0.95, links: ['python'] },
  { id: 'git', label: 'Git', group: 'dev', x: 2.5, y: 1.5, size: 1.0, links: ['github'] },
  { id: 'github', label: 'GitHub', group: 'dev', x: 3.5, y: 2, size: 1.0, links: [] },
  { id: 'mongodb', label: 'MongoDB', group: 'db', x: 3, y: -1, size: 1.0, links: [] },
  { id: 'sql', label: 'SQL', group: 'db', x: 3.5, y: -2.5, size: 1.0, links: ['mongodb'] },
]

export const experience = [
  {
    id: 1,
    title: 'Full Stack Developer Intern',
    org: 'Thiranex',
    duration: 'Apr 27, 2026 – May 26, 2026',
    type: 'internship',
    icon: '🏢',
    description: 'Worked as a Full Stack Developer Intern gaining hands-on experience in end-to-end web development.',
    responsibilities: [
      'Developed and maintained web application features',
      'Collaborated with the development team on full-stack solutions',
      'Applied software engineering best practices in a professional environment',
    ],
    tech: ['Web Development', 'Full Stack', 'Software Engineering'],
    link: 'https://drive.google.com/file/d/1u84u_vkhP_Cbl5bhnzoTSuHCa5feUYiC/view?usp=drive_link',
    featured: true,
  },
  {
    id: 2,
    title: 'AI & RAG Pipeline Development',
    org: 'Personal Projects',
    duration: '2025 – Present',
    type: 'project',
    icon: '🤖',
    description: 'Built production-ready RAG systems using LangChain, FAISS vector stores, and HuggingFace embeddings with Groq LLaMA 3.1 inference.',
    responsibilities: [
      'Designed end-to-end RAG architectures',
      'Implemented semantic search with FAISS',
      'Integrated open-source LLMs via Groq API',
    ],
    tech: ['LangChain', 'FAISS', 'HuggingFace', 'Groq', 'Python'],
    link: null,
    featured: false,
  },
  {
    id: 3,
    title: 'Data Analytics & Visualization',
    org: 'Personal Projects',
    duration: '2025 – Present',
    type: 'project',
    icon: '📊',
    description: 'Designed interactive Power BI dashboards with DAX measures, KPI cards, and drill-through reports for business stakeholders.',
    responsibilities: [
      'Built multi-layered Power BI reports',
      'Created complex DAX formulas for business metrics',
      'Translated business requirements into visual analytics',
    ],
    tech: ['Power BI', 'DAX', 'Excel', 'Data Modeling'],
    link: null,
    featured: false,
  },
  {
    id: 4,
    title: 'Computer Science Student',
    org: 'Sri Krishna College of Engineering and Technology (SKCET)',
    duration: '2022 – 2026',
    type: 'education',
    icon: '🎓',
    description: 'Pursuing B.E. in Computer Science Engineering. Focused on AI, ML, data structures, algorithms, and software engineering principles.',
    responsibilities: [
      'Core CS coursework: Algorithms, OOP, Databases, Networks',
      'AI/ML specialization projects and research',
      'Software engineering practices and team collaboration',
    ],
    tech: ['Python', 'Java', 'Data Structures', 'Algorithms', 'OOP'],
    link: null,
    featured: false,
  },
]

export const research = [
  {
    id: 1,
    topic: 'Retrieval-Augmented Generation (RAG) Systems',
    hypothesis: 'Domain-specific RAG pipelines with fine-tuned embeddings outperform generic LLM responses for specialized knowledge retrieval.',
    approach: 'Experimenting with different chunking strategies, embedding models, and retrieval mechanisms to optimize answer quality.',
    status: 'in-progress',
    tags: ['NLP', 'LLMs', 'Vector Search', 'Python'],
    icon: '🔍',
  },
  {
    id: 2,
    topic: 'NLP for Unstructured Data Analysis',
    hypothesis: 'Combining transformer-based models with domain-specific preprocessing significantly improves entity extraction from unstructured documents.',
    approach: 'Testing open-source NLP models against custom preprocessing pipelines for document understanding tasks.',
    status: 'in-progress',
    tags: ['NLP', 'Transformers', 'Entity Extraction', 'Python'],
    icon: '📝',
  },
  {
    id: 3,
    topic: 'Generative AI for Productivity Tools',
    hypothesis: 'Purpose-built GenAI assistants with constrained knowledge bases provide more reliable outputs than general-purpose models for specific workflows.',
    approach: 'Building specialized GenAI tools with curated knowledge bases and evaluating output reliability vs. hallucination rates.',
    status: 'in-progress',
    tags: ['GenAI', 'LLMs', 'RAG', 'Prompt Engineering'],
    icon: '⚡',
  },
  {
    id: 4,
    topic: 'Healthcare AI — Predictive Analytics',
    hypothesis: 'Ensemble ML models trained on structured healthcare data can provide actionable clinical decision support.',
    approach: 'Extending the Healthcare AI project with more diverse datasets, advanced feature engineering, and model interpretability tools.',
    status: 'in-progress',
    tags: ['ML', 'Healthcare', 'Scikit-learn', 'XAI'],
    icon: '🏥',
  },
]

export const engineeringPipeline = [
  { stage: 'PROBLEM', icon: '🎯', desc: 'Identify and define the core challenge' },
  { stage: 'UNDERSTAND', icon: '🔍', desc: 'Research, analyze requirements, and map constraints' },
  { stage: 'DATA', icon: '📊', desc: 'Gather, clean, and structure the information' },
  { stage: 'MODEL', icon: '🧠', desc: 'Design the solution architecture and approach' },
  { stage: 'EXPERIMENT', icon: '⚗️', desc: 'Build, test, and iterate on prototypes' },
  { stage: 'BUILD', icon: '🔨', desc: 'Implement the production-ready solution' },
  { stage: 'DEPLOY', icon: '🚀', desc: 'Ship to users and monitor performance' },
  { stage: 'IMPROVE', icon: '📈', desc: 'Measure outcomes and refine continuously' },
]

export const contactInfo = {
  email: 'sdharun7010@gmail.com',
  github: 'https://github.com/DharunKumarS-code',
  linkedin: 'https://www.linkedin.com/in/dharun-kumar-8504a4290',
  resume: 'https://drive.google.com/file/d/1L5wJqGGV-p30SEbZ7zgKj3hOGkRmj3At/view?usp=drive_link',
}

export const aiKnowledgeBase = [
  {
    patterns: ['project', 'built', 'work', 'portfolio'],
    response: "Dharun has built 4 main projects: (1) An AI Resume Screening Chatbot using RAG + LangChain + FAISS, (2) A Sales Performance Dashboard in Power BI, (3) A Healthcare AI Solution with Scikit-learn, and (4) A Task Management System in Java. The RAG chatbot is his most technically complex project.",
  },
  {
    patterns: ['skill', 'technology', 'tech', 'know', 'use'],
    response: "Dharun's core stack: Python (AI/ML, automation), LangChain + FAISS (RAG systems), Power BI + DAX (data visualization), Scikit-learn + Pandas (machine learning), Java (software engineering), and Git/GitHub for version control.",
  },
  {
    patterns: ['ai', 'machine learning', 'ml', 'strongest', 'best'],
    response: "His strongest project is the AI Resume Screening Chatbot — it combines RAG architecture, semantic search with FAISS vector stores, HuggingFace embeddings, and Groq LLaMA 3.1 inference, all tied together with a clean Streamlit interface.",
  },
  {
    patterns: ['research', 'exploring', 'studying', 'learning'],
    response: "Dharun is currently exploring: RAG system optimization (chunking strategies, embedding models), NLP for unstructured document analysis, Generative AI for productivity tools, and extending his Healthcare AI project with better ML interpretability.",
  },
  {
    patterns: ['contact', 'reach', 'hire', 'email', 'linkedin'],
    response: "You can reach Dharun at sdharun7010@gmail.com or connect on LinkedIn at linkedin.com/in/dharun-kumar-8504a4290. For his work, check GitHub: github.com/DharunKumarS-code.",
  },
  {
    patterns: ['experience', 'intern', 'job', 'work history'],
    response: "Dharun completed a Full Stack Developer Internship at Thiranex (April–May 2026) and is pursuing his Computer Science degree at SKCET (2022–2026).",
  },
  {
    patterns: ['certif', 'credential', 'course'],
    response: "Dharun holds 7 certifications including: Deloitte Data Analytics Job Simulation, LinkedIn Learning AI courses (Build Your Own GPTs, Intro to AI), TCS iON Interview Skills, Software Engineering Job Simulation by Tom Brunskill, and Data Analyst with ML Essentials from iamneo.",
  },
]
